// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIcq_43jKGU1aRh9U38BIEggCOL7_ZGPc',
    appId: '1:565612190758:web:8978c4d13b53fe56ba1ae7',
    messagingSenderId: '565612190758',
    projectId: 'flaunt-e9ed3',
    authDomain: 'flaunt-e9ed3.firebaseapp.com',
    storageBucket: 'flaunt-e9ed3.appspot.com',
    measurementId: 'G-3Y1W9R0KVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZjXcF1rFhlOnucqEJW1CX24ovyIxl0jI',
    appId: '1:565612190758:android:8b0ea2b5416be16cba1ae7',
    messagingSenderId: '565612190758',
    projectId: 'flaunt-e9ed3',
    storageBucket: 'flaunt-e9ed3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBaHVDhVKsT30RyXjTvCe5miCfpwbfPO8',
    appId: '1:565612190758:ios:7e81b64b82528d9dba1ae7',
    messagingSenderId: '565612190758',
    projectId: 'flaunt-e9ed3',
    storageBucket: 'flaunt-e9ed3.appspot.com',
    androidClientId:
        '565612190758-cd95dd21ameqhiddlgctg67l68dvg8ed.apps.googleusercontent.com',
    iosClientId:
        '565612190758-r2j6qimooslmuvuvpokt2944t1rmj941.apps.googleusercontent.com',
    iosBundleId: 'com.example.flauntEcommenrce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBaHVDhVKsT30RyXjTvCe5miCfpwbfPO8',
    appId: '1:565612190758:ios:7e81b64b82528d9dba1ae7',
    messagingSenderId: '565612190758',
    projectId: 'flaunt-e9ed3',
    storageBucket: 'flaunt-e9ed3.appspot.com',
    androidClientId:
        '565612190758-cd95dd21ameqhiddlgctg67l68dvg8ed.apps.googleusercontent.com',
    iosClientId:
        '565612190758-r2j6qimooslmuvuvpokt2944t1rmj941.apps.googleusercontent.com',
    iosBundleId: 'com.example.flauntEcommenrce',
  );
}
